# Generated by Django 3.2 on 2022-10-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20221010_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_email',
            new_name='customer',
        ),
    ]
