# Generated by Django 3.2 on 2022-10-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20221011_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='apis.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_number',
            field=models.CharField(default='67777777', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.product'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
