# Generated by Django 3.2 on 2022-10-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_placeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceOrder',
        ),
    ]
