# Generated by Django 3.2 on 2022-10-11 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_delete_placeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='apis.customer'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.product'),
        ),
    ]
